# Generated by Django 3.2.3 on 2021-10-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenScoped',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_scoped', models.CharField(max_length=300, verbose_name='Acess Token Scoped')),
            ],
        ),
    ]
