# Generated by Django 3.2.3 on 2021-05-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_spotify_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('capa', models.URLField(max_length=640, verbose_name='Capa')),
                ('musicas', models.JSONField(max_length=640, verbose_name='Músicas')),
                ('links', models.JSONField(max_length=640, verbose_name='Links')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
