# Generated by Django 3.2.3 on 2021-05-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='modificado',
        ),
    ]
