# Generated by Django 3.2.3 on 2021-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210526_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='capa',
            field=models.URLField(max_length=640, null=True, verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
