# Generated by Django 3.2.3 on 2021-05-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clienttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spotify_Client',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
