# Generated by Django 3.2.3 on 2021-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210528_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenScoped',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_scoped', models.CharField(max_length=300, verbose_name='Acess Token Scoped')),
            ],
        ),
    ]
